# Site settings
email: farcasia@gmail.com 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-120263248-1 

# SEO settings
title: Ana Sutii's blogs
description: Personal blog website of Ana Sutii
url: "https://farcasia.github.io/"
twitter_username: https://twitter.com/a_farcasi
default_img: 

# Profile settings
name: Ana Maria Sutii
profile_img: /assets/img/IMG_6239.JPG 
profile: Ana Maria Sutii is a software developer and an amateur improv theater player. 
social:
  github: https://github.com/farcasia
  linkedin: https://www.linkedin.com/in/ana-maria-sutii-7b246a23
  twitter: https://twitter.com/a_farcasi

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
