# Site settings
email: farcasia@gmail.com 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Ana Sutii blogs
description: Personal blog website of Ana Sutii
url: "https://farcasia.github.io/"
twitter_username: a_farcasi
default_img: 

# Profile settings
name: Ana Maria Sutii
profile_img: 
profile: 
social:
  github: farcasia

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
